# Generated by Django 4.0.6 on 2022-07-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collector',
            new_name='trainer',
        ),
        migrations.AddField(
            model_name='collection',
            name='collection',
            field=models.ManyToManyField(related_name='pokemons', to='demo_app.pokemon'),
        ),
    ]
